[passwords]
dsp = "bigdata"
dsp2 = "bigdata2"
abc = "abc123"
xyz = "xyz124"
div = "div123"
"dspbigdata@gmail.com" = "Bigdata@123"

[handles]
dsp = "DSP"
dsp2 = "DSP_2"
abc = "ABC"
xyz = "XYZ"
div = "Divyanshu"
"dspbigdata@gmail.com" = "DSP"
